### ISSUE TITLE
Exceptions for using this theme

### ISSUE THREAD

**Issue by dereklew** [ORRTIZ/ofndtn#1]
FreeMarker template error:
 Template inclusion failed (for parameter value "component://common/webcommon/includes/helplink.ftl"): E:\OfBizTrunk\framework\common\webcommon\includes\helplink.ftl (The system cannot find the path specified)

---

 FTL stack trace ("~" means nesting-related):
- ## Failed at: #include "component://common/webcommo... [in template "component://ofndtn/includes/header.ftl" at line 268, column 21]
  ## Java stack trace (for programmers):
  
  freemarker.core._MiscTemplateException: [... Exception message was already printed; see it above ...]
  at freemarker.core.Include.accept(Include.java:164)
  at freemarker.core.Environment.visit(Environment.java:326)
  at freemarker.core.Environment.visit(Environment.java:332)
  at freemarker.core.Environment.visit(Environment.java:332)
  at freemarker.core.Environment.visit(Environment.java:332)
  at freemarker.core.Environment.process(Environment.java:305)
  at org.ofbiz.base.util.template.FreeMarkerWorker.renderTemplate(FreeMarkerWorker.java:261)
  at org.ofbiz.widget.model.HtmlWidget.renderHtmlTemplate(HtmlWidget.java:167)
  at org.ofbiz.widget.model.HtmlWidget$HtmlTemplate.renderWidgetString(HtmlWidget.java:216)
  at org.ofbiz.widget.model.HtmlWidget.renderWidgetString(HtmlWidget.java:140)
  at org.ofbiz.widget.model.ModelScreenWidget$PlatformSpecific.renderWidgetString(ModelScreenWidget.java:1321)
  at org.ofbiz.widget.model.ModelScreenWidget.renderSubWidgetsString(ModelScreenWidget.java:98)
  at org.ofbiz.widget.model.ModelScreenWidget$Section.renderWidgetString(ModelScreenWidget.java:280)
  at org.ofbiz.widget.model.ModelScreenWidget.renderSubWidgetsString(ModelScreenWidget.java:98)
  at org.ofbiz.widget.model.ModelScreenWidget$Section.renderWidgetString(ModelScreenWidget.java:280)
  at org.ofbiz.widget.model.ModelScreen.renderScreenString(ModelScreen.java:164)
  at org.ofbiz.widget.model.ScreenFactory.renderReferencedScreen(ScreenFactory.java:214)
  at org.ofbiz.widget.model.ModelScreenWidget$IncludeScreen.renderWidgetString(ModelScreenWidget.java:780)
  at org.ofbiz.widget.model.ModelScreenWidget.renderSubWidgetsString(ModelScreenWidget.java:98)
  at org.ofbiz.widget.model.ModelScreenWidget$Section.renderWidgetString(ModelScreenWidget.java:280)
  at org.ofbiz.widget.model.ModelScreen.renderScreenString(ModelScreen.java:164)
  at org.ofbiz.widget.model.ScreenFactory.renderReferencedScreen(ScreenFactory.java:214)
  at org.ofbiz.widget.model.ModelScreenWidget$IncludeScreen.renderWidgetString(ModelScreenWidget.java:780)
  at org.ofbiz.widget.model.ModelScreenWidget.renderSubWidgetsString(ModelScreenWidget.java:98)
  at org.ofbiz.widget.model.ModelScreenWidget$Section.renderWidgetString(ModelScreenWidget.java:280)
  at org.ofbiz.widget.model.ModelScreen.renderScreenString(ModelScreen.java:164)
  at org.ofbiz.widget.model.ScreenFactory.renderReferencedScreen(ScreenFactory.java:214)
  at org.ofbiz.widget.model.ModelScreenWidget$DecoratorScreen.renderWidgetString(ModelScreenWidget.java:860)
  at org.ofbiz.widget.model.ModelScreenWidget.renderSubWidgetsString(ModelScreenWidget.java:98)
  at org.ofbiz.widget.model.ModelScreenWidget$Section.renderWidgetString(ModelScreenWidget.java:280)
  at org.ofbiz.widget.model.ModelScreen.renderScreenString(ModelScreen.java:164)
  at org.ofbiz.widget.model.ScreenFactory.renderReferencedScreen(ScreenFactory.java:214)
  at org.ofbiz.widget.model.ModelScreenWidget$DecoratorScreen.renderWidgetString(ModelScreenWidget.java:860)
  at org.ofbiz.widget.model.ModelScreenWidget.renderSubWidgetsString(ModelScreenWidget.java:98)
  at org.ofbiz.widget.model.ModelScreenWidget$Section.renderWidgetString(ModelScreenWidget.java:280)
  at org.ofbiz.widget.model.ModelScreen.renderScreenString(ModelScreen.java:164)
  at org.ofbiz.widget.renderer.ScreenRenderer.render(ScreenRenderer.java:136)
  at org.ofbiz.widget.renderer.ScreenRenderer.render(ScreenRenderer.java:98)
  at org.ofbiz.widget.renderer.macro.MacroScreenViewHandler.render(MacroScreenViewHandler.java:157)
  at org.ofbiz.webapp.control.RequestHandler.renderView(RequestHandler.java:1001)
  at org.ofbiz.webapp.control.RequestHandler.doRequest(RequestHandler.java:687)
  at org.ofbiz.webapp.control.ControlServlet.doGet(ControlServlet.java:213)
  at org.ofbiz.webapp.control.ControlServlet.doPost(ControlServlet.java:88)
  at javax.servlet.http.HttpServlet.service(HttpServlet.java:648)
  at javax.servlet.http.HttpServlet.service(HttpServlet.java:729)
  at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:292)
  at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:207)
  at org.apache.tomcat.websocket.server.WsFilter.doFilter(WsFilter.java:52)
  at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:240)
  at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:207)
  at org.ofbiz.webapp.control.ContextFilter.doFilter(ContextFilter.java:323)
  at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:240)
  at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:207)
  at org.apache.catalina.core.StandardWrapperValve.invoke(StandardWrapperValve.java:212)
  at org.apache.catalina.core.StandardContextValve.invoke(StandardContextValve.java:106)
  at org.apache.catalina.authenticator.AuthenticatorBase.invoke(AuthenticatorBase.java:502)
  at org.apache.catalina.core.StandardHostValve.invoke(StandardHostValve.java:141)
  at org.apache.catalina.valves.ErrorReportValve.invoke(ErrorReportValve.java:79)
  at org.apache.catalina.core.StandardEngineValve.invoke(StandardEngineValve.java:88)
  at org.apache.catalina.valves.AbstractAccessLogValve.invoke(AbstractAccessLogValve.java:616)
  at org.apache.catalina.connector.CoyoteAdapter.service(CoyoteAdapter.java:522)
  at org.apache.coyote.http11.AbstractHttp11Processor.process(AbstractHttp11Processor.java:1095)
  at org.apache.coyote.AbstractProtocol$AbstractConnectionHandler.process(AbstractProtocol.java:672)
  at org.apache.tomcat.util.net.NioEndpoint$SocketProcessor.doRun(NioEndpoint.java:1502)
  at org.apache.tomcat.util.net.NioEndpoint$SocketProcessor.run(NioEndpoint.java:1458)
  at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
  at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
  at org.apache.tomcat.util.threads.TaskThread$WrappingRunnable.run(TaskThread.java:61)
  at java.lang.Thread.run(Thread.java:745)
  Caused by: java.io.FileNotFoundException: E:\OfBizTrunk\framework\common\webcommon\includes\helplink.ftl (The system cannot find the path specified)
  at java.io.FileInputStream.open0(Native Method)
  at java.io.FileInputStream.open(FileInputStream.java:195)
  at java.io.FileInputStream.<init>(FileInputStream.java:138)
  at java.io.FileInputStream.<init>(FileInputStream.java:93)
  at sun.net.www.protocol.file.FileURLConnection.connect(FileURLConnection.java:90)
  at sun.net.www.protocol.file.FileURLConnection.getInputStream(FileURLConnection.java:188)
  at java.net.URL.openStream(URL.java:1045)
  at org.ofbiz.base.util.template.FreeMarkerWorker.makeReader(FreeMarkerWorker.java:312)
  at org.ofbiz.base.util.template.FreeMarkerWorker.access$000(FreeMarkerWorker.java:76)
  at org.ofbiz.base.util.template.FreeMarkerWorker$FlexibleTemplateLoader.getReader(FreeMarkerWorker.java:676)
  at freemarker.cache.TemplateCache.loadTemplate(TemplateCache.java:546)
  at freemarker.cache.TemplateCache.getTemplateInternal(TemplateCache.java:438)
  at freemarker.cache.TemplateCache.getTemplate(TemplateCache.java:291)
  at freemarker.template.Configuration.getTemplate(Configuration.java:2383)
  at freemarker.core.Environment.getTemplateForInclusion(Environment.java:2478)
  at freemarker.core.Include.accept(Include.java:162)
  ... 68 more

**Comment by PierreSmits** [comment]
Please provide me with details (e.g. version) of the OFBiz implementation the component was applied against.

**Comment by dereklew** [comment]
Hi Pierre, it was the trunk version.

**Comment by dereklew** [comment]
Do i just deploy in the Theme folder, and run ant and load the data?

**Comment by PierreSmits** [comment]
Hi Derek,
I will have some time available soon to investigate the issue. As a lot has changed (in trunk) since I made this theme available I have to spend some time on that.

Yes, you can just put it in the themes folder, or in the hot-deploy folder (as per your choosing). 

After you have deployed the component, you'll still need to execute an ./ant start command to register the webapp with the OFBiz instantiation. Followed by a seed load execution in the webtools compoment, to load the security and theme data. Or you do an ./ant load-seed (but that loads all your seed data from the files again, and might pose a risk when you have changed -parts of that - datasets)first, followed by an ./ant start

**Comment by dereklew** [comment]
Hi Pierre, I did that.  But still encountering those issues, even in the 14.12 build.
